### ISSUE TITLE
cc

### ISSUE THREAD

**Issue by fgsoftware1** [fgsoftware1/calculator-yacc-lex#1]
make  all-recursive
make[1]: Entering directory '/home/fgygh/calculator-yacc-lex'
Making all in src
make[2]: Entering directory '/home/fgygh/calculator-yacc-lex/src'
cc y.tab.c -o ../calculator -lfl
/usr/bin/ld: /tmp/ccKYw6Od.o: in function `yyparse':
y.tab.c:(.text+0x323): undefined reference to `yylex'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:407: ../calculator] Error 1
make[2]: Leaving directory '/home/fgygh/calculator-yacc-lex/src'
make[1]: *** [Makefile:354: all-recursive] Error 1
make[1]: Leaving directory '/home/fgygh/calculator-yacc-lex'
make: *** [Makefile:295: all] Error 2

**Comment by circutrider21** [comment]
The error is because gcc is compiling only 1 file.

**Comment by circutrider21** [comment]
Try manually specifying the file, instead of $< in makefile.am

**Comment by circutrider21** [comment]
Also, automake is being replaced my meson

**Comment by fgsoftware1** [comment]
> The error is because gcc is compiling only 1 file.

the work there is link not compile but i will try

**Comment by fgsoftware1** [comment]
> Try manually specifying the file, instead of $< in makefile.am

this work.
thanks for your help

**Comment by fgsoftware1** [comment]
> Try manually specifying the file, instead of $< in makefile.am

i'm receiving this error now
#3
